### ISSUE TITLE
No releases published

### ISSUE THREAD

**Issue by wolfboy555** [XAYRGA/wsystool#6]
No releases published

**Comment by Decoder0007** [comment]
Build it yourself

**Comment by wolfboy555** [comment]
Cant do that cuz im bad at that stuff and never been taught.

**Comment by Decoder0007** [comment]
Learn then

**Comment by XAYRGA** [comment]
https://xayr.gay/tools/SoundModdingToolkit/7.0.0_EXPERIMENTAL/

I release builds in the toolkits that these are a part of.
